/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DynamicMultiSigValidatorManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminProposalCount"
      | "adminProposals"
      | "admins"
      | "applications"
      | "applyToBeValidator"
      | "getAdminCount"
      | "getAdminProposalSignatures"
      | "getAdmins"
      | "getThreshold"
      | "getValidatorCount"
      | "getValidatorProposalSignatures"
      | "getValidators"
      | "isAdmin"
      | "isValidator"
      | "proposeAddAdmin"
      | "proposeApproval"
      | "proposeRemoval"
      | "proposeRemoveAdmin"
      | "signAdminProposal"
      | "signValidatorProposal"
      | "validatorProposalCount"
      | "validatorProposals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminProposalCreated"
      | "AdminProposalExecuted"
      | "AdminProposalSigned"
      | "AdminRemoved"
      | "ApplicationSubmitted"
      | "ValidatorApproved"
      | "ValidatorProposalCreated"
      | "ValidatorProposalExecuted"
      | "ValidatorProposalSigned"
      | "ValidatorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyToBeValidator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminProposalSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAdmins", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorProposalSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeAddAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeApproval",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeRemoval",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeRemoveAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signAdminProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signValidatorProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validatorProposals",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyToBeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminProposalSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorProposalSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeAddAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeRemoval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeRemoveAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signAdminProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signValidatorProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorProposals",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike, newThreshold: BigNumberish];
  export type OutputTuple = [admin: string, newThreshold: bigint];
  export interface OutputObject {
    admin: string;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    candidate: AddressLike,
    isAddition: boolean
  ];
  export type OutputTuple = [
    proposalId: bigint,
    candidate: string,
    isAddition: boolean
  ];
  export interface OutputObject {
    proposalId: bigint;
    candidate: string;
    isAddition: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, candidate: AddressLike];
  export type OutputTuple = [proposalId: bigint, candidate: string];
  export interface OutputObject {
    proposalId: bigint;
    candidate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminProposalSignedEvent {
  export type InputTuple = [proposalId: BigNumberish, admin: AddressLike];
  export type OutputTuple = [proposalId: bigint, admin: string];
  export interface OutputObject {
    proposalId: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [admin: AddressLike, newThreshold: BigNumberish];
  export type OutputTuple = [admin: string, newThreshold: bigint];
  export interface OutputObject {
    admin: string;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [candidate: AddressLike, organization: string];
  export type OutputTuple = [candidate: string, organization: string];
  export interface OutputObject {
    candidate: string;
    organization: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorApprovedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    candidate: AddressLike,
    isApproval: boolean
  ];
  export type OutputTuple = [
    proposalId: bigint,
    candidate: string,
    isApproval: boolean
  ];
  export interface OutputObject {
    proposalId: bigint;
    candidate: string;
    isApproval: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, candidate: AddressLike];
  export type OutputTuple = [proposalId: bigint, candidate: string];
  export interface OutputObject {
    proposalId: bigint;
    candidate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorProposalSignedEvent {
  export type InputTuple = [proposalId: BigNumberish, admin: AddressLike];
  export type OutputTuple = [proposalId: bigint, admin: string];
  export interface OutputObject {
    proposalId: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRemovedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DynamicMultiSigValidatorManager extends BaseContract {
  connect(runner?: ContractRunner | null): DynamicMultiSigValidatorManager;
  waitForDeployment(): Promise<this>;

  interface: DynamicMultiSigValidatorManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminProposalCount: TypedContractMethod<[], [bigint], "view">;

  adminProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, bigint] & {
        candidate: string;
        isAddition: boolean;
        executed: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  admins: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  applications: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        candidate: string;
        organization: string;
        contactEmail: string;
        submittedAt: bigint;
        isPending: boolean;
      }
    ],
    "view"
  >;

  applyToBeValidator: TypedContractMethod<
    [organization: string, contactEmail: string],
    [void],
    "nonpayable"
  >;

  getAdminCount: TypedContractMethod<[], [bigint], "view">;

  getAdminProposalSignatures: TypedContractMethod<
    [proposalId: BigNumberish],
    [string[]],
    "view"
  >;

  getAdmins: TypedContractMethod<[], [string[]], "view">;

  getThreshold: TypedContractMethod<[], [bigint], "view">;

  getValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getValidatorProposalSignatures: TypedContractMethod<
    [proposalId: BigNumberish],
    [string[]],
    "view"
  >;

  getValidators: TypedContractMethod<[], [string[]], "view">;

  isAdmin: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isValidator: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  proposeAddAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  proposeApproval: TypedContractMethod<
    [candidate: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;

  proposeRemoval: TypedContractMethod<
    [validator: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;

  proposeRemoveAdmin: TypedContractMethod<
    [admin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  signAdminProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  signValidatorProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  validatorProposalCount: TypedContractMethod<[], [bigint], "view">;

  validatorProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, string, bigint] & {
        candidate: string;
        isApproval: boolean;
        executed: boolean;
        reason: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, bigint] & {
        candidate: string;
        isAddition: boolean;
        executed: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        candidate: string;
        organization: string;
        contactEmail: string;
        submittedAt: bigint;
        isPending: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyToBeValidator"
  ): TypedContractMethod<
    [organization: string, contactEmail: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdminCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAdminProposalSignatures"
  ): TypedContractMethod<[proposalId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAdmins"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidatorProposalSignatures"
  ): TypedContractMethod<[proposalId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidator"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposeAddAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeApproval"
  ): TypedContractMethod<
    [candidate: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeRemoval"
  ): TypedContractMethod<
    [validator: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeRemoveAdmin"
  ): TypedContractMethod<[admin: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "signAdminProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signValidatorProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatorProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validatorProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, string, bigint] & {
        candidate: string;
        isApproval: boolean;
        executed: boolean;
        reason: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminProposalCreated"
  ): TypedContractEvent<
    AdminProposalCreatedEvent.InputTuple,
    AdminProposalCreatedEvent.OutputTuple,
    AdminProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AdminProposalExecuted"
  ): TypedContractEvent<
    AdminProposalExecutedEvent.InputTuple,
    AdminProposalExecutedEvent.OutputTuple,
    AdminProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "AdminProposalSigned"
  ): TypedContractEvent<
    AdminProposalSignedEvent.InputTuple,
    AdminProposalSignedEvent.OutputTuple,
    AdminProposalSignedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorApproved"
  ): TypedContractEvent<
    ValidatorApprovedEvent.InputTuple,
    ValidatorApprovedEvent.OutputTuple,
    ValidatorApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorProposalCreated"
  ): TypedContractEvent<
    ValidatorProposalCreatedEvent.InputTuple,
    ValidatorProposalCreatedEvent.OutputTuple,
    ValidatorProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorProposalExecuted"
  ): TypedContractEvent<
    ValidatorProposalExecutedEvent.InputTuple,
    ValidatorProposalExecutedEvent.OutputTuple,
    ValidatorProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorProposalSigned"
  ): TypedContractEvent<
    ValidatorProposalSignedEvent.InputTuple,
    ValidatorProposalSignedEvent.OutputTuple,
    ValidatorProposalSignedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRemoved"
  ): TypedContractEvent<
    ValidatorRemovedEvent.InputTuple,
    ValidatorRemovedEvent.OutputTuple,
    ValidatorRemovedEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address,uint256)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminProposalCreated(uint256,address,bool)": TypedContractEvent<
      AdminProposalCreatedEvent.InputTuple,
      AdminProposalCreatedEvent.OutputTuple,
      AdminProposalCreatedEvent.OutputObject
    >;
    AdminProposalCreated: TypedContractEvent<
      AdminProposalCreatedEvent.InputTuple,
      AdminProposalCreatedEvent.OutputTuple,
      AdminProposalCreatedEvent.OutputObject
    >;

    "AdminProposalExecuted(uint256,address)": TypedContractEvent<
      AdminProposalExecutedEvent.InputTuple,
      AdminProposalExecutedEvent.OutputTuple,
      AdminProposalExecutedEvent.OutputObject
    >;
    AdminProposalExecuted: TypedContractEvent<
      AdminProposalExecutedEvent.InputTuple,
      AdminProposalExecutedEvent.OutputTuple,
      AdminProposalExecutedEvent.OutputObject
    >;

    "AdminProposalSigned(uint256,address)": TypedContractEvent<
      AdminProposalSignedEvent.InputTuple,
      AdminProposalSignedEvent.OutputTuple,
      AdminProposalSignedEvent.OutputObject
    >;
    AdminProposalSigned: TypedContractEvent<
      AdminProposalSignedEvent.InputTuple,
      AdminProposalSignedEvent.OutputTuple,
      AdminProposalSignedEvent.OutputObject
    >;

    "AdminRemoved(address,uint256)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "ApplicationSubmitted(address,string)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "ValidatorApproved(address)": TypedContractEvent<
      ValidatorApprovedEvent.InputTuple,
      ValidatorApprovedEvent.OutputTuple,
      ValidatorApprovedEvent.OutputObject
    >;
    ValidatorApproved: TypedContractEvent<
      ValidatorApprovedEvent.InputTuple,
      ValidatorApprovedEvent.OutputTuple,
      ValidatorApprovedEvent.OutputObject
    >;

    "ValidatorProposalCreated(uint256,address,bool)": TypedContractEvent<
      ValidatorProposalCreatedEvent.InputTuple,
      ValidatorProposalCreatedEvent.OutputTuple,
      ValidatorProposalCreatedEvent.OutputObject
    >;
    ValidatorProposalCreated: TypedContractEvent<
      ValidatorProposalCreatedEvent.InputTuple,
      ValidatorProposalCreatedEvent.OutputTuple,
      ValidatorProposalCreatedEvent.OutputObject
    >;

    "ValidatorProposalExecuted(uint256,address)": TypedContractEvent<
      ValidatorProposalExecutedEvent.InputTuple,
      ValidatorProposalExecutedEvent.OutputTuple,
      ValidatorProposalExecutedEvent.OutputObject
    >;
    ValidatorProposalExecuted: TypedContractEvent<
      ValidatorProposalExecutedEvent.InputTuple,
      ValidatorProposalExecutedEvent.OutputTuple,
      ValidatorProposalExecutedEvent.OutputObject
    >;

    "ValidatorProposalSigned(uint256,address)": TypedContractEvent<
      ValidatorProposalSignedEvent.InputTuple,
      ValidatorProposalSignedEvent.OutputTuple,
      ValidatorProposalSignedEvent.OutputObject
    >;
    ValidatorProposalSigned: TypedContractEvent<
      ValidatorProposalSignedEvent.InputTuple,
      ValidatorProposalSignedEvent.OutputTuple,
      ValidatorProposalSignedEvent.OutputObject
    >;

    "ValidatorRemoved(address)": TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
    ValidatorRemoved: TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
  };
}
