# Docker Compose for Single Besu Validator Node
# Optimized for cloud deployment on constrained resources

version: '3.8'

services:
  besu-node:
    image: hyperledger/besu:latest
    container_name: besu-node
    restart: unless-stopped
    ports:
      - "8545:8545"     # RPC endpoint
      - "30303:30303"   # P2P
    volumes:
      - ./genesis.json:/config/genesis.json:ro
      - ./keys:/config/keys:ro
      - besu-data:/data
    environment:
      - BESU_LOGGING=INFO
      - BESU_OPTS=-Xmx512m -Xms256m -XX:MaxMetaspaceSize=128m
    command:
      - --genesis-file=/config/genesis.json
      - --data-path=/data
      - --node-private-key-file=/config/keys/key
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-api=ETH,NET,WEB3,ADMIN,DEBUG,QBFT
      - --rpc-http-cors-origins=*
      - --host-allowlist=*
      - --p2p-enabled=true
      - --p2p-host=0.0.0.0
      - --p2p-port=30303
      - --min-gas-price=0
    networks:
      besu-net:
        ipv4_address: 172.20.0.10

networks:
  besu-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  besu-data:
